parent_dir: NIAH/Needle_test/Jamba
prompt:
  save_dir: "prompts"
  needle: "\nThe best thing to do in San Francisco is eat a sandwich and sit in Dolores Park on a sunny day.\n"
  haystack_dir: "../PaulGrahamEssays"
  retrieval_question: "What is the best thing to do in San Francisco? Here is the most relevant sentence in the context:"
  context:
    min_len: 250
    max_len: 4096
    interval: 10
    manually_select_list: null  # null or a list of context lengths to manually select
  document_depth:
    min_percent: 0
    max_percent: 100
    interval: 10
    interval_type: "linear"  # "linear", "sigmoid" or null
    manually_select_list: null  # null or a list of document percents to manually select
  tokenizer:
    tokenizer_type: "Huggingface" # "OpenAI", "Anthropic" or "Huggingface"
    model_name:  ai21labs/AI21-Jamba-Mini-1.6 # Change it to your own model name / HF model path
  is_base: false # If prompts are for a base model (basic string) or IT model (chat dict)
  is_jrt: false # if Just-Read-Twice method should be applied.
pred:
  batch_size: 1
  save_dir: "pred"
  sparsification:
    k: [32]
    metric: "entropy"
    prefill: False
  # ckpt_path in notebook
  model_type: "huggingface" # use 'huggingface' for any implemented huggingface model
  model_path: ai21labs/AI21-Jamba-Mini-1.6
eval:
  save_dir: "results"
vis:
  save_dir: "vis"
